# Generated by Django 5.0.6 on 2024-06-28 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lesson_course'),
        ('users', '0004_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='pay_course',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.course', verbose_name='платеж курса'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='pay_lesson',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.lesson', verbose_name='платеж урока'),
        ),
    ]
