# Generated by Django 5.0.6 on 2024-06-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_payments_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='сумма оплаты'),
        ),
    ]
