# Generated by Django 5.0.6 on 2024-07-06 19:32

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_course_course_name_alter_course_course_preview_and_more'),
        ('users', '0009_alter_payments_options_alter_payments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='date_of_pay',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата платежа', verbose_name='Дата платежа'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='pay_course',
            field=models.ForeignKey(blank=True, default=None, help_text='Платеж за курс, возможно выбрать либо курс либо урок', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.course', verbose_name='платеж курса'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='pay_lesson',
            field=models.ForeignKey(blank=True, default=None, help_text='Платеж за урок, возможно выбрать либо курс либо урок', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.lesson', verbose_name='платеж урока'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, help_text='Сумма оплаты, максимум 8 значное число', max_digits=10, verbose_name='сумма оплаты'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'наличные'), ('money_transfer', 'перевод денег')], help_text='Способ оплаты, либо наличные либо денежный перевод', max_length=50, verbose_name='способ оплаты'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='user',
            field=models.ForeignKey(help_text='Владелец платежа', on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Аватар пользователя', null=True, upload_to='users/', verbose_name='аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, help_text='Город проживания пользователя', max_length=150, null=True, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Номер телефона пример "+7(913)0000000"', max_length=128, null=True, region=None, unique=True, verbose_name='номер телефона'),
        ),
    ]
