# Generated by Django 5.0.6 on 2024-07-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_payments_date_of_pay_alter_payments_pay_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='status',
            field=models.CharField(choices=[('sended', 'отправлен'), ('success', 'успешно'), ('cansel', 'отменен')], default='sended', help_text='Статус платежа, возможен только: отправлен, успешен и отменен', max_length=50, verbose_name='статус платежа'),
        ),
    ]
