# Generated by Django 5.0.6 on 2024-07-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_payments_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='id_session',
            field=models.CharField(blank=True, default=None, help_text='ID сессии установленная сервисом Stripe', max_length=256, null=True, verbose_name='Id сессии'),
        ),
    ]
