# Generated by Django 5.0.6 on 2024-07-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_payments_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_amount',
            field=models.DecimalField(decimal_places=0, help_text='Сумма оплаты, максимум 8 значное число', max_digits=12, verbose_name='сумма оплаты'),
        ),
    ]
