# Generated by Django 5.0.6 on 2024-06-26 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200, verbose_name='имя курса')),
                ('course_preview', models.ImageField(blank=True, null=True, upload_to='courses/course/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=200, verbose_name='название урока')),
                ('descriptons', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('lesson_preview', models.ImageField(blank=True, null=True, upload_to='courses/lessons/%Y/%m/%d/', verbose_name='картинка')),
                ('video_link', models.FileField(max_length=256, upload_to='courses/videos/%Y/%m/%d/', verbose_name='ссылка на видео')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='курс')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
            },
        ),
    ]
