# Generated by Django 5.0.6 on 2024-06-26 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_lesson_video_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='descriptons',
            new_name='description',
        ),
    ]
