# Generated by Django 5.0.6 on 2024-07-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_owner_lesson_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_link',
            field=models.CharField(max_length=256, verbose_name='ссылка на видео урок'),
        ),
    ]
