# Generated by Django 5.0.6 on 2024-07-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_course_course_name_alter_course_course_preview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=10000.0, help_text='Стоимость курса, максимум 8 значное число', max_digits=10, verbose_name='стоимость'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=4000.0, help_text='Стоимость урока, максимум 8 значное число', max_digits=10, verbose_name='стоимость'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='course_preview',
            field=models.ImageField(blank=True, help_text='Изображение характеризующее курс', null=True, upload_to='courses/course/%Y/%m/%d/'),
        ),
    ]
