# Generated by Django 5.0.6 on 2024-07-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_amount_lesson_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='amount',
            field=models.DecimalField(decimal_places=0, help_text='Стоимость курса, максимум 8 значное число', max_digits=12, verbose_name='стоимость'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='amount',
            field=models.DecimalField(decimal_places=0, help_text='Стоимость урока, максимум 8 значное число', max_digits=12, verbose_name='стоимость'),
        ),
    ]
